import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const b=await chromium.launch({channel:'chrome',args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await b.newPage({viewport:{width:1365,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.getByRole('heading',{name:'Your coordinates.'}).waitFor();await page.getByText(/mapped features/).waitFor();
await page.screenshot({path:'/tmp/field-atlas-home.png',fullPage:true});
await page.getByRole('button',{name:'Paste coordinates'}).click();
await page.getByLabel('Coordinates',{exact:true}).fill('341099 806040\n341555 806321\n341881 805929');
await page.getByLabel('Zone',{exact:true}).fill('29');
await page.getByRole('button',{name:'Create map'}).click();
await page.getByText('LICENSE CHECK',{exact:true}).waitFor();
await page.waitForTimeout(2500);
const canvas=await page.locator('.maplibregl-canvas').boundingBox();await page.mouse.click(canvas.x+canvas.width/2,canvas.y+canvas.height/2);await page.getByText('LICENCE DETAILS',{exact:true}).waitFor();
const dl=page.waitForEvent('download');await page.getByRole('button',{name:'KML ↓',exact:true}).click();const file=await dl;const content=await fs.readFile(await file.path(),'utf8');assert.match(content,/<Polygon>/);
await page.getByRole('button',{name:'Save to a project'}).click();
await page.getByLabel('Project name').fill('Acceptance Prospect');
await page.getByLabel('Notes').fill('UTM 29N acceptance triangle');
await page.getByRole('button',{name:'Save project',exact:true}).click();
await page.getByRole('button',{name:'Open map',exact:true}).first().click();
await page.waitForTimeout(2500);await page.screenshot({path:'/tmp/field-atlas-map.png',fullPage:true});
const search=page.getByRole('textbox',{name:'Search licences'});await search.fill('Bea Mountain');await page.waitForTimeout(500);
if(await page.locator('.results button').count()){await page.locator('.results button').first().click();await page.getByText('LICENCE DETAILS',{exact:true}).waitFor();}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/field-atlas-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'mobile horizontal overflow');
await page.context().setOffline(true);await page.getByText(/OFFLINE — MME data/).waitFor();await page.getByRole('button',{name:'＋ Coordinates',exact:true}).click();
await page.getByLabel('Coordinates',{exact:true}).fill('7.25 -10.5');await page.getByLabel('Coordinate system').selectOption('decimal');await page.getByLabel('Create as').selectOption('Points');await page.getByRole('button',{name:'Create map'}).click();
await page.getByText(/OFFLINE — MME data/).waitFor();
const offlineDl=page.waitForEvent('download');await page.getByRole('button',{name:'KML ↓',exact:true}).click();assert.match(await fs.readFile(await (await offlineDl).path(),'utf8'),/<Point>/);
await b.close();assert.deepEqual(errors,[]);console.log('Browser smoke passed: UTM polygon, KML export, projects, map, mobile layout, offline conversion/export.');
